# ============================================================================
# AUTO-GENERATED by acsbuild from Threading.Build.cs — DO NOT EDIT BY HAND.
# Edit src/threading/Threading.Build.cs, then run:
#   dotnet run --project tools/acsbuild -- gen
# ============================================================================
acs_module(
    NAME    Threading
    TYPE    Runtime
    SOURCES
        ConditionVar.cpp
        JobGraph.cpp
        Mutex.cpp
        RwLock.cpp
        Thread.cpp
        ThreadPool.cpp
    HEADERS
        Atomic.h
        ConditionVar.h
        JobGraph.h
        JobGraphDiagnostics.h
        MemoryOrder.h
        Mutex.h
        ParallelForDiagnostics.h
        RwLock.h
        ScopedLock.h
        Thread.h
        ThreadAffinity.h
        ThreadId.h
        ThreadPool.h
        ThreadPoolDiagnostics.h
    PUBLIC_DEPS
        Foundation
)

acs_module_feature(MODULE Threading NAME THREADPOOL
    DEFINE THREADING_THREADPOOL
    DESCRIPTION "Build the work-stealing thread pool"
    DEFAULT ON)

acs_module_feature(MODULE Threading NAME LOCKFREE_MPSC
    DEFINE THREADING_LOCKFREE_MPSC
    DESCRIPTION "Build the lock-free MPSC queue (Phase 2 — currently placeholder)"
    DEFAULT OFF)
