# ============================================================================
# AUTO-GENERATED by acsbuild from AssetPack.Build.cs — DO NOT EDIT BY HAND.
# Edit src/assetpack/AssetPack.Build.cs, then run:
#   dotnet run --project tools/acsbuild -- gen
# ============================================================================
acs_module(
    NAME    AssetPack
    TYPE    Runtime
    SOURCES
        AcpakCrypto.cpp
        AcpakDefault.cpp
        AcpakGameBridge.cpp
        AcpakLz4.cpp
        AcpakReader.cpp
        AcpakWriter.cpp
    HEADERS
        AcpakCrypto.h
        AcpakFormat.h
        AcpakGameBridge.h
        AcpakLz4.h
        AcpakReadDiagnostics.h
        AcpakReader.h
        AcpakWriter.h
    PUBLIC_DEPS
        Foundation
        Container
        Memory
        Platform
        Threading
        GameFramework
    LINK_PRIVATE
        Bcrypt
)
