# ============================================================================
# AUTO-GENERATED by acsbuild from App.Build.cs — DO NOT EDIT BY HAND.
# Edit src/app/App.Build.cs, then run:
#   dotnet run --project tools/acsbuild -- gen
# ============================================================================
acs_module(
    NAME    App
    TYPE    Runtime
    SOURCES
        Application.cpp
        ApplicationSubsystemCatalog.cpp
        AssetSubsystem.cpp
        Sample.cpp
        TimerSubsystem.cpp
    HEADERS
        AppConfig.h
        Application.h
        ApplicationSubsystemCatalog.h
        AssetSubsystem.h
        EntryPoint.h
        Sample.h
        TimerSubsystem.h
    PUBLIC_DEPS
        Foundation
        Memory
        Container
        Subsystem
        Threading
        Math
        Platform
        Asset
        Ecs
        Event
        Render
)
