@echo off
rem ============================================================================
rem  ACS clean-up  (clean-up.bat)  -- bulk delete of regenerable junk
rem ----------------------------------------------------------------------------
rem  Deletes build output, intermediate files, IDE caches and scratch files.
rem  Everything removed here is gitignored and regenerated by a build or by
rem  acs\generate.bat, so source / assets / tracked files are never touched.
rem
rem  Sequential rd /s /q is used on purpose: this repo lives on a normal local
rem  disk (C:\dev, NOT OneDrive), and on a single volume parallel deletes give
rem  no speed-up while adding lock/contention risk.
rem
rem  Usage:
rem    clean-up.bat        - list targets, ask Y/N, then delete
rem    clean-up.bat -y     - delete immediately, no prompt (automation)
rem
rem  After cleaning, run  acs\generate.bat  to recreate the solution.
rem ============================================================================
setlocal EnableDelayedExpansion

set "ROOT=%~dp0"
if "%ROOT:~-1%"=="\" set "ROOT=%ROOT:~0,-1%"
set "ACS=%ROOT%\acs"
set /a DEL=0

set "AUTOYES="
if /i "%~1"=="-y" set "AUTOYES=1"
if /i "%~1"=="/y" set "AUTOYES=1"

echo.
echo ==========================================================================
echo  ACS clean-up   (bulk delete)
echo  root: %ROOT%
echo ==========================================================================
echo.
echo  DELETE (regenerable, all gitignored):
echo    [dirs, searched recursively at every level]
echo       cmake-build-*  Binaries  Intermediate  Saved  x64  .vs  out  build
echo    [old out-of-source build trees, repo root only]
echo       b38  sln  sln-test
echo    [scratch files]
echo       build-out.log  configure.log  vc140.pdb  acs_memdump.bmp/svg
echo       persist_progress.sav  persist_settings.ini
echo       loose *.log *.pdb *.obj *.tmp *.ilk  (root + acs)
echo       Thumbs.db / ehthumbs.db (recursive)
echo.
echo  KEPT: source, assets, docs, acs\engine (build system), ACSGame.slnx,
echo        generate.*, .idea (IDE run configs), .git.
echo.

if not defined AUTOYES (
    set /p "ANS=Delete these now? (Y/N): "
    if /i not "!ANS!"=="Y" (
        echo Aborted. Nothing was deleted.
        goto :end
    )
)

echo.
echo --- Deleting --------------------------------------------------------------

rem ===== 1) Build/cache dirs by name, recursively (top-level AND nested) ======
rem NOTE: "cmake-build-*" matches build output; the real CMake modules live in
rem acs\engine\cmake, which is NOT matched and never deleted.
for /d /r "%ROOT%" %%D in (cmake-build-* Binaries Intermediate Saved x64 .vs out build) do call :rmdir "%%~fD"

rem ===== 2) Old out-of-source build trees that only ever sit at the repo root =
call :rmdir "%ROOT%\b38"
call :rmdir "%ROOT%\sln"
call :rmdir "%ROOT%\sln-test"

rem ===== 3) One-off scratch files ============================================
call :rmfile "%ROOT%\acs_memdump.bmp"
call :rmfile "%ROOT%\acs_memdump.svg"
call :rmfile "%ROOT%\configure.log"
call :rmfile "%ROOT%\build-out.log"
call :rmfile "%ROOT%\vc140.pdb"
call :rmfile "%ACS%\build-out.log"
call :rmfile "%ACS%\configure.log"
call :rmfile "%ACS%\src\persist_progress.sav"
call :rmfile "%ACS%\src\persist_settings.ini"
call :rmfile "%ROOT%\persist_progress.sav"
call :rmfile "%ROOT%\persist_settings.ini"

rem ===== 4) Loose intermediate files directly under root / acs ===============
call :rmglob "%ROOT%" "*.log"
call :rmglob "%ROOT%" "*.pdb"
call :rmglob "%ROOT%" "*.tmp"
call :rmglob "%ROOT%" "*.ilk"
call :rmglob "%ACS%"  "*.log"
call :rmglob "%ACS%"  "*.pdb"
call :rmglob "%ACS%"  "*.obj"
call :rmglob "%ACS%"  "*.tmp"
call :rmglob "%ACS%"  "*.ilk"

rem ===== 5) OS noise, removed recursively ===================================
echo   [recurse] Thumbs.db / ehthumbs.db
del /s /q /f /a "%ROOT%\Thumbs.db"   >nul 2>&1
del /s /q /f /a "%ROOT%\ehthumbs.db" >nul 2>&1

echo.
echo --- Done. Removed !DEL! item(s). -----------------------------------------
echo  Run  acs\generate.bat  to recreate the solution.
echo.
goto :end

rem ===========================================================================
rem  Subroutines
rem ===========================================================================
:rmdir
if exist "%~1\" (
    echo   [DIR ] %~1
    rd /s /q "%~1" 2>nul
    if exist "%~1\" rd /s /q "%~1" 2>nul
    set /a DEL+=1
)
exit /b 0

:rmfile
if exist "%~1" (
    echo   [FILE] %~1
    del /q /f "%~1" >nul 2>&1
    set /a DEL+=1
)
exit /b 0

rem  %~1 = directory, %~2 = pattern (that directory's top level only)
:rmglob
if exist "%~1\%~2" (
    echo   [GLOB] %~1\%~2
    del /q /f "%~1\%~2" >nul 2>&1
    set /a DEL+=1
)
exit /b 0

:end
if not defined AUTOYES pause
endlocal
