# ============================================================================
# AUTO-GENERATED by acsbuild from Platform.Build.cs — DO NOT EDIT BY HAND.
# Edit src/platform/Platform.Build.cs, then run:
#   dotnet run --project tools/acsbuild -- gen
# ============================================================================
acs_module(
    NAME    Platform
    TYPE    Runtime
    SOURCES
        FileSystem.cpp
        Input.cpp
        Localization.cpp
        Storage.cpp
        Time.cpp
        Window.cpp
    HEADERS
        Event.h
        FileSystem.h
        Input.h
        InputCodes.h
        Localization.h
        Storage.h
        Time.h
        Window.h
    PUBLIC_DEPS
        Foundation
        Memory
        Container
        Math
    LINK_PRIVATE
        Shell32
        Ole32
)

acs_module_feature(MODULE Platform NAME WINDOW
    DEFINE PLATFORM_WINDOW
    DESCRIPTION "Build Win32 window subsystem"
    DEFAULT ON)

acs_module_feature(MODULE Platform NAME INPUT
    DEFINE PLATFORM_INPUT
    DESCRIPTION "Build keyboard / mouse / gamepad input subsystem"
    DEFAULT ON)
