# ============================================================================
# AUTO-GENERATED by acsbuild from CrashWin.Build.cs — DO NOT EDIT BY HAND.
# Edit src/crashwin/CrashWin.Build.cs, then run:
#   dotnet run --project tools/acsbuild -- gen
# ============================================================================
if(NOT ACS_BUILD_CRASH_REPORTER)
    return()
endif()

acs_module(
    NAME    CrashWin
    TYPE    Runtime
    SOURCES
        WindowsCrashReporter.cpp
        WindowsCrashReporterDefault.cpp
    HEADERS
        WindowsCrashReporter.h
    PUBLIC_DEPS
        Foundation
        GameFramework
    LINK_PUBLIC
        Dbghelp.lib
)
