# ============================================================================
# AUTO-GENERATED by acsbuild from Timing.Build.cs — DO NOT EDIT BY HAND.
# Edit src/timing/Timing.Build.cs, then run:
#   dotnet run --project tools/acsbuild -- gen
# ============================================================================
acs_module(
    NAME    Timing
    TYPE    Runtime
    SOURCES
        FixedStepClock.cpp
        FixedStepClockBatch.cpp
        FixedStepMemoryValidationInternal.cpp
    HEADERS
        FixedStepAdvanceResult.h
        FixedStepClock.h
        FixedStepClockBatch.h
        FixedStepClockSnapshot.h
        FixedStepMemoryRangeInternal.h
        FixedStepMemoryValidationInternal.h
        FixedStepOptions.h
    PUBLIC_DEPS
        Foundation
)
