# ============================================================================
# AUTO-GENERATED by acsbuild from Mvvm.Build.cs — DO NOT EDIT BY HAND.
# Edit src/mvvm/Mvvm.Build.cs, then run:
#   dotnet run --project tools/acsbuild -- gen
# ============================================================================
set(_acsgen_mvvm_sources
    Convert.cpp
    Mvvm.cpp
)
set(_acsgen_mvvm_headers
    Binder.h
    Command.h
    Convert.h
    Derived.h
    Observable.h
    ObservableArray.h
    ViewModel.h
)
set(_acsgen_mvvm_public_deps
    Foundation
    Memory
    Container
    Math
    Threading
)
if(ACS_MVVM_IMGUI_BINDINGS AND ACS_RENDER_DX12_RAW)
    list(APPEND _acsgen_mvvm_sources
        ImguiBindings.cpp
    )
    list(APPEND _acsgen_mvvm_headers
        ImguiBindings.h
    )
    list(APPEND _acsgen_mvvm_public_deps
        Imgui
    )
endif()

acs_module(
    NAME    Mvvm
    TYPE    Runtime
    SOURCES ${_acsgen_mvvm_sources}
    HEADERS ${_acsgen_mvvm_headers}
    PUBLIC_DEPS ${_acsgen_mvvm_public_deps}
)

acs_module_feature(MODULE Mvvm NAME IMGUI_BINDINGS
    DEFINE MVVM_IMGUI_BINDINGS
    DESCRIPTION "Provide ImGui-based binding helpers (acs::mvvm::imgui::Bind*)"
    DEFAULT ${ACS_MVVM_IMGUI_BINDINGS})
