# ============================================================================
# AUTO-GENERATED by acsbuild from Scripting.Build.cs — DO NOT EDIT BY HAND.
# Edit src/scripting/Scripting.Build.cs, then run:
#   dotnet run --project tools/acsbuild -- gen
# ============================================================================
if(NOT ACS_BUILD_SCRIPTING)
    return()
endif()

include(ACSThirdParty)
acs_third_party_lua()

acs_module(
    NAME    Scripting
    TYPE    Runtime
    SOURCES
        LuaDefault.cpp
        LuaVm.cpp
    HEADERS
        LuaVm.h
    PUBLIC_DEPS
        Foundation
        Container
        GameFramework
    LINK_PUBLIC
        acs_third_party_lua
)
