# ============================================================================
# AUTO-GENERATED by acsbuild from Container.Build.cs — DO NOT EDIT BY HAND.
# Edit src/container/Container.Build.cs, then run:
#   dotnet run --project tools/acsbuild -- gen
# ============================================================================
acs_module(
    NAME    Container
    TYPE    Runtime
    SOURCES
        Hash.cpp
        HashBytesBatch.cpp
        Json.cpp
        String.cpp
    HEADERS
        Array.h
        Hash.h
        HashMap.h
        Json.h
        Span.h
        String.h
        StringView.h
    PUBLIC_DEPS
        Foundation
        Memory
)

acs_module_feature(MODULE Container NAME HASHMAP
    DEFINE CONTAINER_HASHMAP
    DESCRIPTION "Include Robin-Hood THashMap"
    DEFAULT ON)

acs_module_feature(MODULE Container NAME STRING_SSO
    DEFINE CONTAINER_STRING_SSO
    DESCRIPTION "Use small-string optimization for FString (22 inline bytes)"
    DEFAULT ON)
