# ============================================================================
# AUTO-GENERATED by acsbuild from Subsystem.Build.cs — DO NOT EDIT BY HAND.
# Edit src/subsystem/Subsystem.Build.cs, then run:
#   dotnet run --project tools/acsbuild -- gen
# ============================================================================
acs_module(
    NAME    Subsystem
    TYPE    Runtime
    SOURCES
        Subsystem.cpp
        SubsystemCollection.cpp
        SubsystemRegistry.cpp
    HEADERS
        Subsystem.h
        SubsystemCollection.h
        SubsystemFactory.h
        SubsystemFrameContext.h
        SubsystemOwner.h
        SubsystemRegistry.h
        SubsystemScope.h
        SubsystemTickPhase.h
    PUBLIC_DEPS
        Foundation
        Memory
        Container
)
