# ============================================================================
# AUTO-GENERATED by acsbuild from Ecs.Build.cs — DO NOT EDIT BY HAND.
# Edit src/ecs/Ecs.Build.cs, then run:
#   dotnet run --project tools/acsbuild -- gen
# ============================================================================
acs_module(
    NAME    Ecs
    TYPE    Runtime
    SOURCES
        ComponentRegistry.cpp
        World.cpp
    HEADERS
        ComponentId.h
        ComponentRegistry.h
        Entity.h
        EntityCommandBuffer.h
        ParallelEntityCommandBuffer.h
        Query.h
        RollbackBuffer.h
        SparseSet.h
        System.h
        World.h
    PUBLIC_DEPS
        Foundation
        Memory
        Container
        Threading
)
