// SPDX-License-Identifier: Apache-2.0
// GameFramework Pillar A — まとめ include
//
// `#include "gameframework/GameFramework.h"` 1 行で v1 の Pillar A を全部
// 引き込める。
#pragma once

#include "gameframework/Game.h"
#include "gameframework/Scene.h"
#include "gameframework/Scene2D.h"
#include "gameframework/LegacyScene3DAdapter.h"
#include "gameframework/SceneManager.h"
#include "gameframework/RenderContext.h"
#include "gameframework/AppState.h"
#include "gameframework/Easing.h"
#include "gameframework/Clock.h"
#include "gameframework/Tween.h"
#include "gameframework/Sequence.h"
#include "gameframework/StateMachine.h"
#include "gameframework/Transform2D.h"
#include "gameframework/AComponent.h"
#include "gameframework/ANode.h"
#include "gameframework/InputMap.h"
#include "gameframework/Camera2D.h"
#include "gameframework/CollisionWorld2D.h"
#include "gameframework/PhysicsBody2D.h"
#include "gameframework/Sprite2DComponent.h"
#include "gameframework/SpriteAnimComponent.h"
#include "gameframework/TriggerComponent.h"
#include "gameframework/TilemapComponent.h"
#include "gameframework/Effects2D.h"
#include "gameframework/WaterSurface3DComponent.h"
#include "gameframework/SceneServices.h"

#include "gameframework/NodeId.h"
#include "gameframework/Pool.h"
#include "gameframework/Random.h"
#include "gameframework/DebugDraw.h"
#include "gameframework/PhotoMode.h"
#include "gameframework/AmbientDirector.h"
#include "gameframework/SpriteAnimator.h"
#include "gameframework/EffectSystem.h"
#include "gameframework/AssetBundle.h"
#include "gameframework/BehaviorTree.h"
#include "gameframework/Entitlement.h"
#include "gameframework/AudioDirector.h"
#include "gameframework/SaveSlot.h"
#include "gameframework/ModRegistry.h"
#include "gameframework/SteamworksBridge.h"
#include "gameframework/BackendClient.h"
#include "gameframework/MlRuntime.h"
#include "gameframework/Settings.h"
#include "gameframework/PartySystem.h"
#include "gameframework/DevConsole.h"

#include "gameframework/FadeTransition.h"
#include "gameframework/SceneEventBus.h"
#include "gameframework/StreamingDirector.h"
#include "gameframework/OpenXrBridge.h"
#include "gameframework/StudioWorkflow.h"
#include "gameframework/Lockstep.h"
#include "gameframework/UiLayer.h"
#include "gameframework/Pathfinding.h"
#include "gameframework/Tilemap.h"
#include "gameframework/WeatherSystem.h"
#include "gameframework/DamageFeedback.h"
#include "gameframework/WorkshopBridge.h"
#include "gameframework/LlmSafetyPipeline.h"
#include "gameframework/TutorialFlow.h"
#include "gameframework/DialogueSystem.h"

#include "gameframework/SceneTimer.h"
#include "gameframework/TriggerWorld2D.h"
#include "gameframework/AssetPack.h"
#include "gameframework/PrefabSystem.h"
#include "gameframework/CameraStack.h"
#include "gameframework/LocalizationDirector.h"
#include "gameframework/AchievementManager.h"
#include "gameframework/DebugOverlay.h"
#include "gameframework/ParticleEffectSystem.h"
#include "gameframework/MusicDirector.h"
#include "gameframework/AccessibilityProfile.h"
#include "gameframework/PrivacyDirector.h"
#include "gameframework/CinematicsDirector.h"
#include "gameframework/InspectorSeam.h"
#include "gameframework/Progression.h"

#include "gameframework/AnimationCurve.h"
#include "gameframework/AnimationCurveArchive.h"
#include "gameframework/InputRecorder.h"
#include "gameframework/Perception.h"
#include "gameframework/SeasonPass.h"
#include "gameframework/VoiceChat.h"
#include "gameframework/TypeInfo.h"
#include "gameframework/PauseDirector.h"
#include "gameframework/HotReload.h"
#include "gameframework/PerfBudget.h"
#include "gameframework/SceneCommandQueue.h"
#include "gameframework/SocialModeration.h"
#include "gameframework/SpatialAudio.h"
#include "gameframework/CameraShakePresets.h"
#include "gameframework/ContentModerator.h"
#include "gameframework/DialogueLocalizer.h"

#include "gameframework/WaterVolume.h"
#include "gameframework/CrashReporter.h"
#include "gameframework/TelemetryDirector.h"
#include "gameframework/GameFlow.h"
#include "gameframework/DynamicDifficulty.h"
#include "gameframework/ReplayDirector.h"
#include "gameframework/SpritePack.h"
#include "gameframework/EconomyDirector.h"
#include "gameframework/CharacterCustomizer.h"
#include "gameframework/CombatStateMachine.h"

#include "gameframework/HealthSystem.h"
#include "gameframework/InventorySystem.h"
#include "gameframework/CooldownTimer.h"
#include "gameframework/BuffSystem.h"
#include "gameframework/ScoreSystem.h"
#include "gameframework/WaveSpawner.h"
#include "gameframework/PickupSystem.h"
#include "gameframework/WeaponSystem.h"
#include "gameframework/ProjectileSystem.h"
#include "gameframework/NodePool.h"

#include "gameframework/DeckSystem.h"
#include "gameframework/BeatGrid.h"
#include "gameframework/DungeonGenerator.h"
#include "gameframework/LapTimer.h"
#include "gameframework/CraftingSystem.h"
#include "gameframework/MatchGrid.h"
#include "gameframework/TurnManager.h"
#include "gameframework/CheckpointSystem.h"
#include "gameframework/HungerSystem.h"
#include "gameframework/DialogueScript.h"

#include "gameframework/EntryPoint.h"
