# ============================================================================
# AUTO-GENERATED by acsbuild from Event.Build.cs — DO NOT EDIT BY HAND.
# Edit src/event/Event.Build.cs, then run:
#   dotnet run --project tools/acsbuild -- gen
# ============================================================================
acs_module(
    NAME    Event
    TYPE    Runtime
    SOURCES
        MessageBroker.cpp
        Timer.cpp
    HEADERS
        MessageBroker.h
        MessagePipe.h
        Timer.h
    PUBLIC_DEPS
        Foundation
        Container
        Threading
)
