# ============================================================================
# AUTO-GENERATED by acsbuild from Event.Build.cs — DO NOT EDIT BY HAND.
# Edit src/event/Event.Build.cs, then run:
#   dotnet run --project tools/acsbuild -- gen
# ============================================================================
acs_module(
    NAME    Event
    TYPE    Runtime
    SOURCES
        MessageBroker.cpp
        TimerManager.cpp
        TypedEvent.cpp
    HEADERS
        Delegate.h
        EventTypeId.h
        MessageBroker.h
        MessagePipe.h
        MessagePipePolicy.h
        MulticastDelegate.h
        SimpleDelegate.h
        SimpleMulticastDelegate.h
        SubscriptionHandle.h
        Timer.h
        TimerDiagnostics.h
        TimerHandle.h
        TimerManager.h
        TimerSchedulePolicy.h
        TypedEvent.h
        TypedEventCallback.h
        TypedEventHandle.h
        TypedEventSlot.h
        TypedEventState.h
        TypedEventSubscription.h
    PUBLIC_DEPS
        Foundation
        Container
        Threading
        Memory
)
