# ============================================================================
# AUTO-GENERATED by acsbuild from Asset.Build.cs — DO NOT EDIT BY HAND.
# Edit src/asset/Asset.Build.cs, then run:
#   dotnet run --project tools/acsbuild -- gen
# ============================================================================
acs_third_party_stb()
acs_third_party_cgltf()
acs_third_party_ufbx()
acs_third_party_drlibs()

acs_module(
    NAME    Asset
    TYPE    Runtime
    SOURCES
        AssetRegistry.cpp
        AudioAsset.cpp
        BinaryAsset.cpp
        ImageAsset.cpp
        MeshAsset.cpp
        MeshPrimitive.cpp
        SkinnedMesh.cpp
        TextAsset.cpp
    HEADERS
        Asset.h
        AssetFuture.h
        AssetId.h
        AssetRegistry.h
        AudioAsset.h
        BinaryAsset.h
        IAssetLoader.h
        ImageAsset.h
        MeshAsset.h
        MeshPrimitive.h
        SkinnedMesh.h
        TextAsset.h
    PUBLIC_DEPS
        Foundation
        Memory
        Container
        Threading
        Math
        Platform
    LINK_PRIVATE
        acs_third_party::stb
        acs_third_party::cgltf
        acs_third_party::ufbx
        acs_third_party::drlibs
)
