# SPDX-License-Identifier: Apache-2.0
include_guard(GLOBAL)
include(FetchContent)

# Windowsの対象CPUから公式配布のdirectory名を返す。不明なCPUやbit数の不一致は失敗する。
function(acs_dxc_architecture output)
    if(NOT WIN32)
        message(FATAL_ERROR "ACS: DXC runtime requires Windows")
    endif()
    # Visual Studioではhost CPUでなくgeneratorの対象CPUを優先する。
    if(CMAKE_VS_PLATFORM_NAME)
        set(architecture "${CMAKE_VS_PLATFORM_NAME}")
    elseif(CMAKE_CXX_COMPILER_ARCHITECTURE_ID)
        set(architecture "${CMAKE_CXX_COMPILER_ARCHITECTURE_ID}")
    elseif(CMAKE_C_COMPILER_ARCHITECTURE_ID)
        set(architecture "${CMAKE_C_COMPILER_ARCHITECTURE_ID}")
    else()
        set(architecture "${CMAKE_SYSTEM_PROCESSOR}")
    endif()
    string(TOLOWER "${architecture}" architecture)
    if(architecture MATCHES "^(x64|amd64|x86_64)$")
        set(architecture x64)
        set(pointer_size 8)
    elseif(architecture MATCHES "^(arm64|aarch64)$")
        set(architecture arm64)
        set(pointer_size 8)
    elseif(architecture MATCHES "^(win32|x86|i[3-6]86)$")
        set(architecture x86)
        set(pointer_size 4)
    else()
        message(FATAL_ERROR "ACS: unsupported DXC target architecture: ${architecture}")
    endif()
    if(NOT CMAKE_SIZEOF_VOID_P EQUAL pointer_size)
        message(FATAL_ERROR "ACS: DXC target architecture/pointer size mismatch: ${architecture}/${CMAKE_SIZEOF_VOID_P}")
    endif()
    set(${output} "${architecture}" PARENT_SCOPE)
endfunction()

# 必須fileの存在、内容、取得root内の実体を確認する。SDKやPATHによる補完はしない。
function(acs_dxc_require_file root relative)
    set(required_file "${root}/${relative}")
    if(NOT EXISTS "${required_file}" OR IS_DIRECTORY "${required_file}")
        message(FATAL_ERROR "ACS: required DXC file missing: ${required_file}")
    endif()
    file(REAL_PATH "${root}" real_root)
    file(REAL_PATH "${required_file}" real_file)
    cmake_path(IS_PREFIX real_root "${real_file}" NORMALIZE within_root)
    if(NOT within_root)
        message(FATAL_ERROR "ACS: DXC file escapes the fetched root: ${required_file}")
    endif()
    file(SIZE "${required_file}" required_size)
    if(required_size EQUAL 0)
        message(FATAL_ERROR "ACS: required DXC file is empty: ${required_file}")
    endif()
endfunction()

# RawDX12用の固定版を取得し、headerだけを提供する。呼出し側はPRIVATEにlinkする。
function(acs_third_party_dxc)
    if(NOT ACS_RENDER_DX12_RAW OR TARGET acs_third_party::dxc)
        return()
    endif()
    acs_dxc_architecture(architecture)
    # 任意のlocal配布へ差し替えて固定hashの検証を省略することは許可しない。
    if(FETCHCONTENT_SOURCE_DIR_ACS_DXC OR FETCHCONTENT_SOURCE_DIR_ACS_DXCN OR FETCHCONTENT_SOURCE_DIR_ACS_DXCL)
        message(FATAL_ERROR "ACS: DXC source overrides bypass the pinned official distribution")
    endif()
    FetchContent_Declare(acs_dxc URL "https://github.com/microsoft/DirectXShaderCompiler/releases/download/v1.9.2602.24/dxc_2026_05_27.zip" URL_HASH SHA256=cf658aacf070d3045e31b8f1f8a696c2945f37c1095019481ef7c513368db3b4 DOWNLOAD_EXTRACT_TIMESTAMP FALSE)
    # ZIPに含まれない第三者表記を同じ公式tagからhash固定で補完する。
    # 依存名は短く保つ。CMake 3.24のsubbuildでは名前がstamp path内に繰り返される。
    FetchContent_Declare(acs_dxcn URL "https://raw.githubusercontent.com/microsoft/DirectXShaderCompiler/v1.9.2602.24/ThirdPartyNotices.txt" URL_HASH SHA256=19512a5d0a015ef16d167272c164da49a604614a786206212a80ad486ed0be6d DOWNLOAD_NO_EXTRACT TRUE)
    # ZIPの短縮版licenseにないMiniz/Unicode等の表記も公式sourceの全文で保持する。
    FetchContent_Declare(acs_dxcl URL "https://raw.githubusercontent.com/microsoft/DirectXShaderCompiler/v1.9.2602.24/LICENSE.TXT" URL_HASH SHA256=27a49e35d1da96eba18fba54bc882667ff0ff8c0254f16f2b6e165d605ba7df8 DOWNLOAD_NO_EXTRACT TRUE DOWNLOAD_NAME LICENSE-DXC-Source.txt)
    FetchContent_MakeAvailable(acs_dxc acs_dxcn acs_dxcl)

    # compilerとvalidatorを同じ取得root、同じCPUの組で保持する。
    set(runtime_files "${acs_dxc_SOURCE_DIR}/bin/${architecture}/dxcompiler.dll" "${acs_dxc_SOURCE_DIR}/bin/${architecture}/dxil.dll")
    foreach(relative IN ITEMS inc/dxcapi.h inc/d3d12shader.h "bin/${architecture}/dxcompiler.dll" "bin/${architecture}/dxil.dll" LICENSE-LLVM.txt LICENSE-MIT.txt LICENSE-MS.txt inc/hlsl/LICENSE.txt ReleaseNotes.md)
        acs_dxc_require_file("${acs_dxc_SOURCE_DIR}" "${relative}")
    endforeach()
    acs_dxc_require_file("${acs_dxcn_SOURCE_DIR}" ThirdPartyNotices.txt)
    acs_dxc_require_file("${acs_dxcl_SOURCE_DIR}" LICENSE-DXC-Source.txt)
    # Diligent同梱版のlicenseと混在させないため版名付きdirectoryへ配布する。
    # ReleaseNotesの適用対応表も保持する。file同梱の成功は商用出荷全体の適合判定ではない。
    set(license_files "${acs_dxc_SOURCE_DIR}/LICENSE-LLVM.txt" "${acs_dxc_SOURCE_DIR}/LICENSE-MIT.txt" "${acs_dxc_SOURCE_DIR}/LICENSE-MS.txt" "${acs_dxc_SOURCE_DIR}/inc/hlsl/LICENSE.txt" "${acs_dxc_SOURCE_DIR}/ReleaseNotes.md" "${acs_dxcn_SOURCE_DIR}/ThirdPartyNotices.txt" "${acs_dxcl_SOURCE_DIR}/LICENSE-DXC-Source.txt")
    set_property(GLOBAL PROPERTY ACS_DXC_RUNTIME_FILES "${runtime_files}")
    set_property(GLOBAL PROPERTY ACS_DXC_LICENSE_FILES "${license_files}")
    set_property(GLOBAL PROPERTY ACS_DXC_LICENSE_DIRECTORY "Licenses/ThirdParty/DXC-v1.9.2602.24")
    add_library(acs_third_party_dxc INTERFACE)
    target_include_directories(acs_third_party_dxc INTERFACE "${acs_dxc_SOURCE_DIR}/inc")
    add_library(acs_third_party::dxc ALIAS acs_third_party_dxc)
endfunction()

# exeまたはEditorABI等のDLL横へ両DLLとlicenseを置く。OFFでは何もせず、欠落時はbuildを失敗させる。
# add_executable/add_libraryの後にacs_dxc_runtime(<target>)を呼ぶ。配置だけ失われた再buildにも対応する。
function(acs_dxc_runtime target)
    if(NOT ACS_RENDER_DX12_RAW)
        return()
    endif()
    acs_third_party_dxc()
    if(NOT TARGET "${target}")
        message(FATAL_ERROR "ACS: DXC runtime target not found: ${target}")
    endif()
    get_target_property(target_type "${target}" TYPE)
    get_target_property(is_imported "${target}" IMPORTED)
    if(is_imported OR NOT target_type MATCHES "^(EXECUTABLE|SHARED_LIBRARY|MODULE_LIBRARY)$")
        message(FATAL_ERROR "ACS: DXC runtime needs a built executable or DLL: ${target}")
    endif()
    get_target_property(runtime_registered "${target}" ACS_DXC_RUNTIME_REGISTERED)
    if(runtime_registered)
        return()
    endif()
    get_property(runtime_files GLOBAL PROPERTY ACS_DXC_RUNTIME_FILES)
    get_property(license_files GLOBAL PROPERTY ACS_DXC_LICENSE_FILES)
    get_property(license_directory GLOBAL PROPERTY ACS_DXC_LICENSE_DIRECTORY)
    # 毎回copy_if_differentで確認し、exeに再linkが不要でも消えた配布fileを復元する。
    add_custom_target(${target}_acs_dxc_runtime COMMAND "${CMAKE_COMMAND}" -E make_directory "$<TARGET_FILE_DIR:${target}>/${license_directory}" COMMAND "${CMAKE_COMMAND}" -E copy_if_different ${runtime_files} "$<TARGET_FILE_DIR:${target}>" COMMAND "${CMAKE_COMMAND}" -E copy_if_different ${license_files} "$<TARGET_FILE_DIR:${target}>/${license_directory}" COMMENT "DXC runtimeとlicenseを${target}へ配置" VERBATIM)
    set_target_properties(${target}_acs_dxc_runtime PROPERTIES FOLDER "Engine/Generated")
    add_dependencies(${target} ${target}_acs_dxc_runtime)
    set_property(TARGET "${target}" PROPERTY ACS_DXC_RUNTIME_REGISTERED TRUE)
endfunction()

# ゲームの配布先へ動的読込DLLとlicenseを必須登録する。欠落はinstall/CPackでも失敗する。
function(acs_dxc_install_runtime destination)
    if(NOT ACS_RENDER_DX12_RAW)
        return()
    endif()
    acs_third_party_dxc()
    get_property(runtime_files GLOBAL PROPERTY ACS_DXC_RUNTIME_FILES)
    get_property(license_files GLOBAL PROPERTY ACS_DXC_LICENSE_FILES)
    get_property(license_directory GLOBAL PROPERTY ACS_DXC_LICENSE_DIRECTORY)
    install(FILES ${runtime_files} DESTINATION "${destination}" COMPONENT ACSGameRuntime)
    install(FILES ${license_files} DESTINATION "${destination}/${license_directory}" COMPONENT ACSGameRuntime)
endfunction()
