# ============================================================================
# AUTO-GENERATED by acsbuild from LocalMatch.Build.cs — DO NOT EDIT BY HAND.
# Edit src/localmatch/LocalMatch.Build.cs, then run:
#   dotnet run --project tools/acsbuild -- gen
# ============================================================================
if(NOT ACS_BUILD_LOCAL_MATCHMAKER)
    return()
endif()

acs_module(
    NAME    LocalMatch
    TYPE    Runtime
    SOURCES
        LocalMatchmaker.cpp
        LocalMatchmakerDefault.cpp
    HEADERS
        LocalMatchmaker.h
    PUBLIC_DEPS
        Foundation
        GameFramework
)
