# ============================================================================
# AUTO-GENERATED by acsbuild from TelemetryFile.Build.cs — DO NOT EDIT BY HAND.
# Edit src/telemetryfile/TelemetryFile.Build.cs, then run:
#   dotnet run --project tools/acsbuild -- gen
# ============================================================================
if(NOT ACS_BUILD_TELEMETRY_FILE)
    return()
endif()

acs_module(
    NAME    TelemetryFile
    TYPE    Runtime
    SOURCES
        FileTelemetryBackendClient.cpp
        FileTelemetryDefault.cpp
    HEADERS
        FileTelemetryBackendClient.h
    PUBLIC_DEPS
        Foundation
        GameFramework
)
