# ============================================================================
# AUTO-GENERATED by acsbuild from Ui.Build.cs — DO NOT EDIT BY HAND.
# Edit src/ui/Ui.Build.cs, then run:
#   dotnet run --project tools/acsbuild -- gen
# ============================================================================
acs_module(
    NAME    Ui
    TYPE    Runtime
    SOURCES
        UiRenderer.cpp
    HEADERS
        UiRenderer.h
        Widget.h
        Widgets.h
    PUBLIC_DEPS
        Foundation
        Memory
        Container
        Math
        Platform
        Render
        Mvvm
)
