# ============================================================================
# AUTO-GENERATED by acsbuild from Easy.Build.cs — DO NOT EDIT BY HAND.
# Edit src/easy/Easy.Build.cs, then run:
#   dotnet run --project tools/acsbuild -- gen
# ============================================================================
acs_module(
    NAME    Easy
    TYPE    Runtime
    SOURCES
        Easy.cpp
    HEADERS
        Easy.h
    PUBLIC_DEPS
        Foundation
        Threading
        Memory
        Container
        Math
        Platform
        Asset
        Render
        Audio
)
