# ============================================================================
# AUTO-GENERATED by acsbuild from Foundation.Build.cs — DO NOT EDIT BY HAND.
# Edit src/foundation/Foundation.Build.cs, then run:
#   dotnet run --project tools/acsbuild -- gen
# ============================================================================
acs_module(
    NAME    Foundation
    TYPE    Runtime
    SOURCES
        Assert.cpp
        Log.cpp
        LogSinkSubscription.cpp
        Panic.cpp
        StackTrace.cpp
    HEADERS
        EnumTraits.h
        Assert.h
        Cast.h
        Compiler.h
        EndianSerialization.h
        EnumLookup.h
        Error.h
        GenerationHandleLayoutTraits.h
        Limits.h
        Log.h
        LogSinkHandle.h
        LogSinkSubscription.h
        Move.h
        Panic.h
        Platform.h
        Result.h
        SourceLoc.h
        StackTrace.h
        TypeTraits.h
        Types.h
    LINK_PUBLIC
        dbghelp
)

acs_module_feature(MODULE Foundation NAME STACKTRACE
    DEFINE FOUNDATION_STACKTRACE
    DESCRIPTION "Capture stack traces via DbgHelp on panic / assert"
    DEFAULT ON)

acs_module_feature(MODULE Foundation NAME LOG_FILE_SINK
    DEFINE FOUNDATION_LOG_FILE
    DESCRIPTION "Enable file output sink in Logger"
    DEFAULT ON)

acs_module_feature(MODULE Foundation NAME LOG_DEBUG_OUTPUT
    DEFINE FOUNDATION_LOG_DBGOUT
    DESCRIPTION "Enable OutputDebugString sink in Logger"
    DEFAULT ON)
