# ============================================================================
# AUTO-GENERATED by acsbuild from OpenXr.Build.cs — DO NOT EDIT BY HAND.
# Edit src/openxr/OpenXr.Build.cs, then run:
#   dotnet run --project tools/acsbuild -- gen
# ============================================================================
if(NOT ACS_BUILD_OPENXR)
    return()
endif()

include(ACSThirdParty)
acs_third_party_openxr()

acs_module(
    NAME    OpenXr
    TYPE    Runtime
    SOURCES
        KhronosOpenXrBridge.cpp
        OpenXrDefault.cpp
    HEADERS
        KhronosOpenXrBridge.h
    PUBLIC_DEPS
        Foundation
        Math
        GameFramework
    LINK_PUBLIC
        acs_third_party_openxr
)
