# SPDX-License-Identifier: Apache-2.0
# Compatibility wrapper.
#
# The old version of this script generated one engine solution plus one solution
# per sample under <repo>/sln/. That layout is intentionally retired. ACS now has
# one beginner-facing solution generated by acs/generate.ps1:
#
#   acs/Intermediate/vs/ACS.slnx
#
# Keep this wrapper so old shortcuts still work, but route everything through the
# single-solution generator.

[CmdletBinding()]
param(
    [string]$Generator = "Visual Studio 18 2026",
    [string]$OutDir   = "",
    [string]$Sample   = "",
    [switch]$EngineOnly,
    [switch]$NoDiligent,
    [switch]$Force,
    [switch]$Open,
    [switch]$AllBackends
)

$ErrorActionPreference = "Stop"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot  = (Resolve-Path "$ScriptDir\..").Path
$Generate  = Join-Path $RepoRoot "acs\generate.ps1"

if ($OutDir) {
    Write-Warning "-OutDir is ignored. The single ACS solution is generated under acs/Intermediate/vs."
}
if ($Sample) {
    Write-Warning "-Sample is ignored. The single ACS solution contains all enabled samples."
}
if ($EngineOnly) {
    Write-Warning "-EngineOnly is ignored. The single ACS solution contains engine, samples, tools and tests."
}

$args = @("-Generator", $Generator)
if ($Force) { $args += "-Clean" }
if ($Open) { $args += "-Open" }
if (-not $NoDiligent) { $args += "-Diligent" }
if ($AllBackends) { $args += "-AllBackends" }

& powershell -NoProfile -ExecutionPolicy Bypass -File $Generate @args
exit $LASTEXITCODE
