# SPDX-License-Identifier: Apache-2.0
# 製品の作成器を別プロセスへ移し、作業場所にDLLがあっても配置欠落を隠さないことを確認する。
if(NOT IS_ABSOLUTE "${PROBE}" OR NOT EXISTS "${PROBE}" OR NOT IS_ABSOLUTE "${ARTIFACT_ROOT}")
    message(FATAL_ERROR "DXC isolation: 検査実行物と保存先には絶対パスが必要です。")
endif()
get_filename_component(probe_directory "${PROBE}" DIRECTORY)
get_filename_component(probe_name "${PROBE}" NAME)
foreach(runtime IN ITEMS dxcompiler.dll dxil.dll)
    if(NOT EXISTS "${probe_directory}/${runtime}")
        message(FATAL_ERROR "DXC isolation: 正常系の配布DLLがありません: ${runtime}")
    endif()
endforeach()

foreach(scenario IN ITEMS complete missing-both missing-compiler missing-validator)
    set(directory "${ARTIFACT_ROOT}/${scenario}")
    file(MAKE_DIRECTORY "${directory}")
    file(COPY_FILE "${PROBE}" "${directory}/${probe_name}" ONLY_IF_DIFFERENT)
    foreach(runtime IN ITEMS dxcompiler.dll dxil.dll)
        if(scenario STREQUAL "complete" OR (scenario STREQUAL "missing-compiler" AND runtime STREQUAL "dxil.dll") OR (scenario STREQUAL "missing-validator" AND runtime STREQUAL "dxcompiler.dll"))
            file(COPY_FILE "${probe_directory}/${runtime}" "${directory}/${runtime}" ONLY_IF_DIFFERENT)
        elseif(EXISTS "${directory}/${runtime}")
            # 古い配置を自動削除して試験条件を作り替えず、汚染した条件を明示する。
            message(FATAL_ERROR "DXC isolation: 欠落条件の場所に予期しないDLLがあります: ${directory}/${runtime}")
        endif()
    endforeach()
    if(scenario STREQUAL "complete")
        set(arguments)
    else()
        set(arguments --expect-missing-runtime)
    endif()
    # 作業場所には両DLLがある。そこを暗黙検索してしまう実装なら欠落条件で失敗する。
    execute_process(COMMAND "${directory}/${probe_name}" ${arguments} WORKING_DIRECTORY "${probe_directory}" RESULT_VARIABLE result OUTPUT_FILE "${directory}/result.log" ERROR_FILE "${directory}/errors.log" TIMEOUT 30)
    if(NOT result STREQUAL "0")
        message(FATAL_ERROR "DXC isolation: ${scenario} failed (${result}); ${directory}/result.log を参照してください。")
    endif()
    message(STATUS "DXC isolation: ${scenario} passed")
endforeach()
