# ============================================================================
# AUTO-GENERATED by acsbuild from Steamworks.Build.cs — DO NOT EDIT BY HAND.
# Edit src/steamworks/Steamworks.Build.cs, then run:
#   dotnet run --project tools/acsbuild -- gen
# ============================================================================
if(NOT ACS_BUILD_STEAMWORKS)
    return()
endif()

include(ACSThirdParty)
acs_third_party_steamworks()

acs_module(
    NAME    Steamworks
    TYPE    Runtime
    SOURCES
        SteamworksBridgeImpl.cpp
        SteamworksDefault.cpp
    HEADERS
        SteamworksBridgeImpl.h
    PUBLIC_DEPS
        Foundation
        GameFramework
    LINK_PUBLIC
        acs_third_party_steamworks
)
