# ============================================================================
# AUTO-GENERATED by acsbuild from Render.Build.cs — DO NOT EDIT BY HAND.
# Edit src/render/Render.Build.cs, then run:
#   dotnet run --project tools/acsbuild -- gen
# ============================================================================
# stb (truetype) はフォントのアトラス焼きで使うので Render でも fetch する
acs_third_party_stb()

# トップレベルの ACS_RENDER_DILIGENT が ON のときだけ Diligent を fetch する。
if(ACS_RENDER_DILIGENT)
    acs_third_party_diligent()
endif()

set(_acsgen_render_sources
    Atmosphere.cpp
    Blit.cpp
    BurnEffect.cpp
    DebugDraw.cpp
    Font.cpp
    Fxaa.cpp
    HiZ.cpp
    Ibl.cpp
    Light2D.cpp
    MotionVector.cpp
    Particles.cpp
    PbrShader.cpp
    PostProcess.cpp
    RefractionShader.cpp
    RenderAssets.cpp
    RenderGraphTransientAlias.cpp
    Renderer.cpp
    ShadowMap.cpp
    SkinnedShader.cpp
    Sky.cpp
    SpriteBatch.cpp
    SpriteSortList.cpp
    Ssao.cpp
    Ssgi.cpp
    Ssr.cpp
    StandardShader.cpp
    SubstrateExpression.cpp
    SubstrateMaterial.cpp
    SubsurfaceScattering.cpp
    VertexScatter.cpp
    WaterSurface3D.cpp
)
set(_acsgen_render_headers
    Atmosphere.h
    Blit.h
    BurnEffect.h
    DebugDraw.h
    DescriptorSlotPool.h
    Font.h
    FormatAspect.h
    FormatTraits.h
    Fxaa.h
    HiZ.h
    IRhiBuffer.h
    IRhiCommandList.h
    IRhiDevice.h
    IRhiPipeline.h
    IRhiSampler.h
    IRhiShader.h
    IRhiSwapchain.h
    IRhiTexture.h
    Ibl.h
    Light2D.h
    MotionVector.h
    NormalMatrix.h
    Particles.h
    PbrShader.h
    PipelineStateKey.h
    PipelineStateKeyCache.h
    PostProcess.h
    RefractionShader.h
    Render.h
    RenderAssets.h
    RenderGraphAliasAssignment.h
    RenderGraphAliasPlanSummary.h
    RenderGraphResourceLifetime.h
    RenderGraphTransientAlias.h
    Renderer.h
    RhiPipelineBindDomain.h
    RhiPipelineBindPolicy.h
    RhiTypes.h
    ShaderParameterLayoutMetadata.h
    ShadowMap.h
    SkinnedShader.h
    Sky.h
    SpriteBatch.h
    SpriteSortList.h
    Ssao.h
    Ssgi.h
    Ssr.h
    StandardShader.h
    SubstrateExpression.h
    SubstrateMaterial.h
    SubsurfaceScattering.h
    TemporalHistory.h
    VertexScatter.h
    WaterSurface3D.h
)
set(_acsgen_render_public_deps
    Foundation
    Memory
    Container
    Math
    Platform
    Asset
)
set(_acsgen_render_link_private
    acs_third_party::stb
)
if(ACS_RENDER_DX12_RAW)
    list(APPEND _acsgen_render_sources
        Dx12/Dx12Buffer.cpp
        Dx12/Dx12CommandList.cpp
        Dx12/Dx12Device.cpp
        Dx12/Dx12Pipeline.cpp
        Dx12/Dx12Shader.cpp
        Dx12/Dx12Swapchain.cpp
        Dx12/Dx12Texture.cpp
    )
    list(APPEND _acsgen_render_link_private
        d3d12
        dxgi
        d3dcompiler
        dxguid
    )
endif()
if(ACS_RENDER_DILIGENT)
    list(APPEND _acsgen_render_sources
        Diligent/DiligentBackend.cpp
        Diligent/DiligentBuffer.cpp
        Diligent/DiligentCommandList.cpp
        Diligent/DiligentDevice.cpp
        Diligent/DiligentMemoryAdapter.cpp
        Diligent/DiligentPipeline.cpp
        Diligent/DiligentShader.cpp
        Diligent/DiligentSwapchain.cpp
        Diligent/DiligentTexture.cpp
    )
    list(APPEND _acsgen_render_link_private
        acs_third_party::diligent_core
    )
endif()
if(ACS_RENDER_DILIGENT AND WIN32)
    list(APPEND _acsgen_render_link_private
        d3d12
        dxgi
        dxguid
    )
endif()

acs_module(
    NAME    Render
    TYPE    Runtime
    SOURCES ${_acsgen_render_sources}
    HEADERS ${_acsgen_render_headers}
    PUBLIC_DEPS ${_acsgen_render_public_deps}
    LINK_PRIVATE ${_acsgen_render_link_private}
)

acs_module_feature(MODULE Render NAME DX12_RAW
    DEFINE RENDER_DX12_RAW
    DESCRIPTION "Use raw DirectX 12 backend"
    DEFAULT ${ACS_RENDER_DX12_RAW})

acs_module_feature(MODULE Render NAME DILIGENT
    DEFINE RENDER_DILIGENT
    DESCRIPTION "Use Diligent Engine as RHI backend (DX12/Vulkan/Metal cross-platform)"
    DEFAULT ${ACS_RENDER_DILIGENT})

acs_module_feature(MODULE Render NAME DILIGENT_VULKAN
    DEFINE RENDER_DILIGENT_VULKAN
    DESCRIPTION "Build Diligent Vulkan backend (only meaningful with ACS_RENDER_DILIGENT=ON)"
    DEFAULT ${ACS_DILIGENT_VULKAN})
