# ============================================================================
# AUTO-GENERATED by acsbuild from MlOnnx.Build.cs — DO NOT EDIT BY HAND.
# Edit src/mlonnx/MlOnnx.Build.cs, then run:
#   dotnet run --project tools/acsbuild -- gen
# ============================================================================
if(NOT ACS_BUILD_ML_ONNX)
    return()
endif()

include(ACSThirdParty)
acs_third_party_onnxruntime()

acs_module(
    NAME    MlOnnx
    TYPE    Runtime
    SOURCES
        OnnxDefault.cpp
        OnnxMlRuntime.cpp
    HEADERS
        OnnxMlRuntime.h
    PUBLIC_DEPS
        Foundation
        GameFramework
    LINK_PUBLIC
        acs_third_party_onnxruntime
)
