# ============================================================================
# AUTO-GENERATED by acsbuild from Test.Build.cs — DO NOT EDIT BY HAND.
# Edit src/test/Test.Build.cs, then run:
#   dotnet run --project tools/acsbuild -- gen
# ============================================================================
acs_module(
    NAME    Test
    TYPE    Test
    SOURCES
        Test.cpp
    HEADERS
        Expect.h
        Test.h
    PUBLIC_DEPS
        Foundation
        Threading
        Container
)
