# SPDX-License-Identifier: Apache-2.0
# Amalgamate ACS public headers into a single self-contained header: dist/acs.h
#
#   python acs/scripts/amalgamate.py            # report external-include surface only
#   python acs/scripts/amalgamate.py --write    # also write dist/acs.h
#
# Design: a mini-preprocessor. It inlines every ACS `#include "..."` depth-first
# with a global seen-set (mimicking #pragma once), strips `#pragma once`, and
# leaves external `#include <...>` lines exactly where they are (they are
# idempotent via their own include guards, so no hoisting / dedup is needed and
# any surrounding `#if` context is preserved). Backend-internal headers
# (render/Dx12, render/Diligent) and the unit-test harness are excluded — only
# the public, backend-agnostic API is amalgamated.
import os, re, sys, glob

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", "..")).replace("\\", "/")  # repo root
SRC  = ROOT + "/acs/src"

EXCLUDE_SUBSTR = ["/Dx12/", "/Diligent/", "/test/"]

def excluded(rel):
    return rel.endswith("Internal.h") or any(s in ("/" + rel) for s in EXCLUDE_SUBSTR)

inc_re  = re.compile(r'^\s*#\s*include\s+"([^"]+)"\s*(?://.*)?$')
ext_re  = re.compile(r'^\s*#\s*include\s+<([^>]+)>\s*(?://.*)?$')
once_re = re.compile(r'^\s*#\s*pragma\s+once\s*$')

seen = set()
out = []
externals = {}
unresolved = []

def resolve(rel, from_path):
    for base in (SRC, os.path.dirname(from_path)):
        cand = os.path.normpath(os.path.join(base, rel)).replace("\\", "/")
        if os.path.exists(cand):
            return cand
    return None

def inline(path):
    path = path.replace("\\", "/")
    if path in seen:
        return
    seen.add(path)
    rel = path[len(SRC) + 1:] if path.startswith(SRC) else path
    out.append("\n// ===================== " + rel + " =====================\n")
    with open(path, encoding="utf-8", errors="replace") as f:
        for line in f:
            if once_re.match(line):
                continue
            m = inc_re.match(line)
            if m:
                tgt = resolve(m.group(1), path)
                if tgt is None:
                    unresolved.append((rel, m.group(1)))
                    out.append(line)
                elif excluded(tgt[len(SRC) + 1:] if tgt.startswith(SRC) else tgt):
                    out.append("// [amalgam] skipped internal include: " + m.group(1) + "\n")
                else:
                    inline(tgt)
                continue
            e = ext_re.match(line)
            if e:
                externals[e.group(1)] = externals.get(e.group(1), 0) + 1
            out.append(line)

roots = sorted(p.replace("\\", "/") for p in glob.glob(SRC + "/**/*.h", recursive=True)
               if not excluded(p.replace("\\", "/")[len(SRC) + 1:]))
for r in roots:
    inline(r)

print("=== external <...> includes pulled into amalgamation ===")
for h, c in sorted(externals.items()):
    print(f"  {c:4d}  <{h}>")
if unresolved:
    print("=== UNRESOLVED quoted includes (left literal — fix these) ===")
    for f, r in unresolved[:30]:
        print(f'  {f} -> "{r}"')
print(f"\nheaders inlined: {len(seen)}   output lines: {len(out)}")

if "--write" in sys.argv:
    os.makedirs(ROOT + "/dist", exist_ok=True)
    banner = '''// SPDX-License-Identifier: Apache-2.0
// =============================================================================
// ACS Engine - Single-Header Amalgamation  (acs.h)
// -----------------------------------------------------------------------------
//   #include <acs.h>   // + add dist/ to include & library search paths
// Auto-links acs.lib and the required Windows system libraries.
// GENERATED by acs/scripts/amalgamate.py from acs/src public headers - do not edit.
// =============================================================================
#pragma once

// ---- ABI guards: ACS is built with exceptions + RTTI disabled (no-STL engine).
//      A consumer TU MUST match, or layouts/mangling diverge. Fail fast & clear.
#if defined(_MSC_VER)
  #if defined(_CPPUNWIND)
    #error "ACS requires exceptions disabled. Compile with: /EHs-c- /D_HAS_EXCEPTIONS=0"
  #endif
  #if defined(_CPPRTTI)
    #error "ACS requires RTTI disabled. Compile with: /GR-"
  #endif
#endif

#if defined(_MSC_VER)
  #pragma comment(lib, "acs.lib")
  #pragma comment(lib, "d3d12.lib")
  #pragma comment(lib, "dxgi.lib")
  #pragma comment(lib, "d3dcompiler.lib")
  #pragma comment(lib, "dxguid.lib")
  #pragma comment(lib, "xaudio2.lib")
  #pragma comment(lib, "ws2_32.lib")
  #pragma comment(lib, "ole32.lib")
  #pragma comment(lib, "dbghelp.lib")
  #pragma comment(lib, "winmm.lib")
  #pragma comment(lib, "user32.lib")
  #pragma comment(lib, "gdi32.lib")
  // ---- Diligent RHI backend (built with ACS_RENDER_DILIGENT=ON). These static
  //      libs are shipped in dist/lib/x64/<cfg> next to acs.lib; the consumer's
  //      library search path picks them up. Sky/Atmosphere compute pipelines and
  //      the Diligent device factory live here.
  #pragma comment(lib, "Diligent-GraphicsEngineD3D12-static.lib")
  #pragma comment(lib, "Diligent-GraphicsEngineD3DBase.lib")
  #pragma comment(lib, "Diligent-GraphicsEngineNextGenBase.lib")
  #pragma comment(lib, "Diligent-GraphicsEngine.lib")
  #pragma comment(lib, "Diligent-GraphicsTools.lib")
  #pragma comment(lib, "Diligent-Archiver-static.lib")
  #pragma comment(lib, "Diligent-ShaderTools.lib")
  #pragma comment(lib, "Diligent-GraphicsAccessories.lib")
  #pragma comment(lib, "Diligent-Common.lib")
  #pragma comment(lib, "Diligent-Win32Platform.lib")
  #pragma comment(lib, "Diligent-BasicPlatform.lib")
  #pragma comment(lib, "Diligent-Primitives.lib")
  #pragma comment(lib, "xxhash.lib")
  #pragma comment(lib, "Shlwapi.lib")
#endif
'''
    with open(ROOT + "/dist/acs.h", "w", encoding="utf-8") as f:
        f.write(banner)
        f.write("".join(out))
    print("wrote " + ROOT + "/dist/acs.h")
