# ============================================================================
# AUTO-GENERATED by acsbuild from Memory.Build.cs — DO NOT EDIT BY HAND.
# Edit src/memory/Memory.Build.cs, then run:
#   dotnet run --project tools/acsbuild -- gen
# ============================================================================
acs_module(
    NAME    Memory
    TYPE    Runtime
    SOURCES
        ArenaAllocator.cpp
        LinearAllocator.cpp
        Memory.cpp
        MemorySnapshot.cpp
        MemorySystem.cpp
        PoolAllocator.cpp
        RelocatableAllocator.cpp
        ShardedTlsf.cpp
        SystemAllocator.cpp
        Tlsf.cpp
        VirtualMemory.cpp
    HEADERS
        Allocator.h
        ArenaAllocator.h
        LinearAllocator.h
        Memory.h
        MemorySnapshot.h
        MemorySystem.h
        New.h
        ObjectPool.h
        ObjectPtr.h
        PoolAllocator.h
        Rc.h
        RelocatableAllocator.h
        Segment.h
        ShardedTlsf.h
        SharedPtr.h
        SystemAllocator.h
        Tlsf.h
        UniquePtr.h
        VirtualMemory.h
    PUBLIC_DEPS
        Foundation
        Threading
)

acs_module_feature(MODULE Memory NAME LINEAR_ALLOCATOR
    DEFINE MEMORY_LINEAR_ALLOC
    DESCRIPTION "Include LinearAllocator"
    DEFAULT ON)

acs_module_feature(MODULE Memory NAME POOL_ALLOCATOR
    DEFINE MEMORY_POOL_ALLOC
    DESCRIPTION "Include PoolAllocator"
    DEFAULT ON)

acs_module_feature(MODULE Memory NAME ARENA_ALLOCATOR
    DEFINE MEMORY_ARENA_ALLOC
    DESCRIPTION "Include ArenaAllocator"
    DEFAULT ON)

acs_module_feature(MODULE Memory NAME VIRTUAL_MEMORY
    DEFINE MEMORY_VIRTUAL_MEM
    DESCRIPTION "VirtualAlloc reserve+commit layer"
    DEFAULT ON)

acs_module_feature(MODULE Memory NAME TLSF
    DEFINE MEMORY_TLSF
    DESCRIPTION "TLSF allocator"
    DEFAULT ON)

acs_module_feature(MODULE Memory NAME SEGMENT_SYSTEM
    DEFINE MEMORY_SEGMENT_SYS
    DESCRIPTION "Segmented MemorySystem"
    DEFAULT ON)

acs_module_feature(MODULE Memory NAME SNAPSHOT
    DEFINE MEMORY_SNAPSHOT
    DESCRIPTION "Memory usage snapshot output"
    DEFAULT ON)
