# ============================================================================
# AUTO-GENERATED by acsbuild from Collision.Build.cs — DO NOT EDIT BY HAND.
# Edit src/collision/Collision.Build.cs, then run:
#   dotnet run --project tools/acsbuild -- gen
# ============================================================================
acs_module(
    NAME    Collision
    TYPE    Runtime
    SOURCES
        ConvexHull3.cpp
        MeshCollider.cpp
        SpriteCollider.cpp
    HEADERS
        ConvexHull3.h
        MeshCollider.h
        SpriteCollider.h
    PUBLIC_DEPS
        Foundation
        Container
        Math
        Asset
)
