# ============================================================================
# AUTO-GENERATED by acsbuild from Network.Build.cs — DO NOT EDIT BY HAND.
# Edit src/network/Network.Build.cs, then run:
#   dotnet run --project tools/acsbuild -- gen
# ============================================================================
acs_module(
    NAME    Network
    TYPE    Runtime
    SOURCES
        Network.cpp
        TcpConnection.cpp
        TcpListener.cpp
        UdpSocket.cpp
    HEADERS
        IpAddress.h
        Network.h
        TcpConnection.h
        TcpListener.h
        UdpSocket.h
    PUBLIC_DEPS
        Foundation
        Memory
        Container
    LINK_PUBLIC
        ws2_32
)
